version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: audiobookshelf-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - audiobookshelf
    restart: unless-stopped
    networks:
      - abs_network

  audiobookshelf:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: audiobookshelf-app
    # Remove external port exposure since nginx will handle it
    expose:
      - "80"
    volumes:
      - audiobooks:/audiobooks
      - podcasts:/podcasts
      - metadata:/metadata
      - config:/config
      - type: bind
        source: /path/to/your/libraries
        target: /libraries
    environment:
      - TZ=America/New_York
      - PUID=1000
      - PGID=1000
      - PORT=80
      - HOST=0.0.0.0
    restart: unless-stopped
    networks:
      - abs_network
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:80/ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

networks:
  abs_network:
    driver: bridge

volumes:
  audiobooks:
    name: audiobookshelf_audiobooks
  podcasts:
    name: audiobookshelf_podcasts
  metadata:
    name: audiobookshelf_metadata
  config:
    name: audiobookshelf_config 